#!/usr/bin/env python3

import asyncio
from websockets.sync.client import connect
import ssl
import pathlib

import logging
logger = logging.getLogger('websockets')
logger.setLevel(logging.DEBUG)
logger.addHandler(logging.StreamHandler())


class JitsiBot:
    def __init__(self, uri, id, password):
        """
        Initialize the Jitsi bot.
        
        :param uri: The full URI of the Jitsi meeting room
        :param id: Bot ID for server to know whos joinning
        :param password: Password for bot ID 
        """
        self.uri = uri
        self.id = id
        self.password = password

    def start(self):
        try:
            # set tls
            #ssl_context = ssl.SSLContext(ssl.PROTOCOL_TLS_CLIENT)
            #cert_path = pathlib.Path(__file__).with_name("jitsi-local.pem") # I HATE TLS
            #ssl_context.load_verify_locations(cert_path)

            # ignore tls
            ssl_context = ssl.create_default_context()
            ssl_context.check_hostname = False
            ssl_context.verify_mode = ssl.CERT_NONE

            with connect(self.uri, ssl=ssl_context, subprotocols=["xmpp"]) as websocket:
                #text = '<open xmlns="urn:ietf:params:xml:ns:xmpp-framing" to="jitsi.local" version="1.0"/>'
                #text = '<open to="jitsi.local" version="1.0" xmlns="urn:ietf:params:xml:ns:xmpp-framing"/>'
                #text = '<message to="stunningmemosadvanceyet@conference.jitsi.local" type="groupchat" xmlns="jabber:client"><body>cock and balls</body></message>'
                #websocket.send(text)
                #print(f">>> {text}")
                #message = websocket.recv()
                #print(f"<<< {message}")
                
                #"""
                #text = f'''
                #<presence to="stunningmemosadvanceyet@conference.jitsi.local/da355bcc" xmlns="jabber:client">
                #    <x xmlns="http://jabber.org/protocol/muc"/>
                #        <stats-id>
                #            Glenna-EJF
                #        </stats-id>
                #        <c hash="sha-1" node="https://jitsi.org/jitsi-meet" ver="+mpajJhafj8jFogLBKsPbQfMgzU=" xmlns="http://jabber.org/protocol/caps"/>
                #        <SourceInfo>
                #            {{}}
                #        </SourceInfo>
                #        <jitsi_participant_codecList>vp8,h264,av1,vp9</jitsi_participant_codecList>
                #        <nick xmlns="http://jabber.org/protocol/nick">bot nick</nick>
                #</presence>
                #'''
                #websocket.send(text)
                #"""

                text = '<open to="jitsi.local" version="1.0" xmlns="urn:ietf:params:xml:ns:xmpp-framing"/>'
                websocket.send(text)

                text = '<auth mechanism="ANONYMOUS" xmlns="urn:ietf:params:xml:ns:xmpp-sasl"/>'
                websocket.send(text)

                #text = '<open to="jitsi.local" version="1.0" xmlns="urn:ietf:params:xml:ns:xmpp-framing"/>'
                #websocket.send(text)

                #text = '<iq id="_bind_auth_2" type="set" xmlns="jabber:client"><bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"/></iq>'
                #websocket.send(text)

                #text = '<iq id="_session_auth_2" type="set" xmlns="jabber:client"><session xmlns="urn:ietf:params:xml:ns:xmpp-session"/></iq>'
                #websocket.send(text)

                #text = '<enable resume="true" xmlns="urn:xmpp:sm:3"/>'
                #websocket.send(text)

                """
                text = f'''
                <iq id="b176dbaa-5372-47f7-94cf-9ee236fc4904:sendIQ" to="jitsi.local" type="get" xmlns="jabber:client">
                    <services xmlns="urn:xmpp:extdisco:2"/>
                </iq>
                '''
                websocket.send(text)
                """

                """
                text = f'''
                <iq from="klap8yf2934r64shxmdeh5pu@jitsi.local/7-N5H2ierM8H" id="bde206d2-c8c6-4e11-b66e-06415464a80e:sendIQ" to="jitsi.local" type="get" xmlns="jabber:client">
                    <query xmlns="http://jabber.org/protocol/disco#info"/>
                </iq>
                '''
                websocket.send(text)
                """

                """
                text = f'''
                <iq id="cdaaf3ab-332e-45f1-9071-84f4bfbf1378:sendIQ" to="focus.jitsi.local" type="set" xmlns="jabber:client">
                    <conference machine-uid="0717265bb0024cab91f0ba929d9b9975" room="stunningmemosadvanceyet@conference.jitsi.local" xmlns="http://jitsi.org/protocol/focus">
                        <property name="rtcstatsEnabled" value="false"/>
                        <property name="visitors-version" value="1"/>
                    </conference>
                </iq>
                '''
                websocket.send(text)
                """

                """
                text = f'''
                <iq from="klap8yf2934r64shxmdeh5pu@jitsi.local/7-N5H2ierM8H" id="c6a785c2-51c1-4965-b7e7-9e8e1ce4844e:sendIQ" to="breakout.jitsi.local" type="get" xmlns="jabber:client">
                    <query node="breakout_rooms" xmlns="http://jabber.org/protocol/disco#info"/>
                </iq>
                '''
                websocket.send(text)
                """

                """
                text = f'''
                <iq from="klap8yf2934r64shxmdeh5pu@jitsi.local/7-N5H2ierM8H" id="6d0626c0-5ee2-4e55-8757-ef15721f1a76:sendIQ" to="lobby.jitsi.local" type="get" xmlns="jabber:client">
                    <query node="lobbyrooms" xmlns="http://jabber.org/protocol/disco#info"/>
                </iq>
                '''
                websocket.send(text)
                """

                #text = '<r xmlns="urn:xmpp:sm:3"/>'
                #websocket.send(text)

                """
                text = '''
                <presence to="stunningmemosadvanceyet@conference.jitsi.local/7e175593" xmlns="jabber:client">
                    <x xmlns="http://jabber.org/protocol/muc"/>
                    <stats-id>Glenna-EJF</stats-id>
                    <c hash="sha-1" node="https://jitsi.org/jitsi-meet" ver="+mpajJhafj8jFogLBKsPbQfMgzU=" xmlns="http://jabber.org/protocol/caps"/>
                    <SourceInfo>{{}}</SourceInfo><jitsi_participant_codecList>vp8,h264,av1,vp9</jitsi_participant_codecList>
                    <nick xmlns="http://jabber.org/protocol/nick">balls</nick>
                </presence>
                '''
                websocket.send(text)
                """
                
                
                #message = websocket.recv()
                #print(f"<<< {message}")
            
            # Enter display name
            #self.driver.find_element(By.ID, "premeeting-name-input").send_keys(self.id)
            #print(f"Entered name: {self.id}")

            # Enter password (if required)
            #password_input = self.driver.find_element(By.ID, "")
            #password_input.send_keys(self.password)
            #print(f"Entered password: {self.password}")

            # Click Join
            #self.driver.find_element(By.XPATH, "//div[@data-testid='prejoin.joinMeeting']").click()
            #print("Joinned room via button")
            
        except Exception as e:
            print(f"Error: {e}")
            #import traceback
            #traceback.print_exc()
    
"""
    # prob wont need to mute/unmute the bot
    def toggle_audio(self):
        try:
            mute_button = self.driver.find_element(By.CLASS_NAME, "audio-preview")
            if mute_button:
                mute_button.click()
                print("Audio toggled")
        except Exception as e:
            print(f"Error muting audio: {e}")
    

    # I have it here but I don't think I'll get any use out of it
    def toggle_video(self):
        try:
            video_button = self.driver.find_element(By.CLASS_NAME, "video-preview") 
            if video_button:
                video_button.click()
                print("Video toggled")
        except Exception as e:
            print(f"Error toggling video: {e}")


    def send_message(self, message):
        try:
            self.driver.find_element(By.XPATH, "/html/body/div/div/div/div/div[3]/div/div/div/div[4]").click() # click icon
            chat_input = self.driver.find_element(By.ID, "chat-input-messagebox") # select prompt
            if chat_input:
                chat_input.send_keys(message)
                chat_input.send_keys(Keys.RETURN)
                time.sleep(1)
                self.driver.find_element(By.XPATH, "/html/body/div/div/div/div/div[3]/div/div/div/div[4]").click() # click icon again to close
                print(f"Message sent: {message}")
        except Exception as e:
            print(f"Error sending message: {e}")
    

    # TODO fix asap
    def get_participants(self):
        try:
            participants_list = self.driver.find_element(By.XPATH, "//div[contains(@class, 'participants')]") 
            print("Participants:")
        except Exception as e:
            print(f"Error getting participants: {e}")
    

    def stop(self):
        if self.driver:
            self.driver.quit()
            print("Bot stopped")
"""

if __name__ == "__main__":
    # Bot config
    XMPP_DOMAIN = "meet.jitsi.local"
    #ROOM = "testroom"
    #ROOM = "StunningMemosAdvanceYet"
    ROOM = "testroom"

    WS_URI = f"wss://{XMPP_DOMAIN}/xmpp-websocket?room={ROOM}"
    ID = f"bot"
    PASSWORD = "botpassword"
    #VITRUAL_AUDIO_DEVICE = "BotSink"
    
    # Create bot instance
    bot = JitsiBot(WS_URI, ID, PASSWORD)
    
    try:
        bot.start()
        #bot.send_message("Hello from Jitsi Bot!")
        #time.sleep(1000000)
        
    except KeyboardInterrupt:
        #bot.stop()
        print("Interrupted by user")
    #finally:
    #    bot.stop()
